### ISSUE TITLE
MongoDb Connector based on official driver

### ISSUE THREAD

**Issue by iozozturk** [akka/alpakka#115]
Hi all,

I know that MongoDb connector is already mentioned and closed at #43 . I think not everybody is using that driver for MongoDb.

I have been using [official driver](http://mongodb.github.io/mongo-scala-driver/) for a while and it is good and reactive. It also has a compatibility with [reactive streams](http://mongodb.github.io/mongo-scala-driver/1.2/integrations/) whereas it requires a bit of manual copy paste work, which is not elegant.

I can take part if you think it is reasonable. What do you think?

**Comment by johanandren** [comment]
Is there any significant pros with using the official driver over the reactivemongo driver?

**Comment by iozozturk** [comment]
I don't think there is whereas people might feel safer to go with the official driver. And there are already applications using official driver. Since reactive mongo is an external connector, should they mix one more driver(reactivemongo) as a dependency to be able to use the Alpakka mongo connector?

**Comment by patriknw** [comment]
@iozozturk I don't mind listing both alternatives. Will you create a PR?

**Comment by iozozturk** [comment]
@patriknw Ok I will create a PR for this

**Comment by stephennancekivell** [comment]
I'd also like to see this. Reactive mongo is currently based on akka (2.3.x) without scala 2.12. Where mongo-scala-driver is netty based with current 2.12.
So there maybe benefits with dependency versions.

It also looks like there are some performance benefits in the mongo-scala-driver.
http://evojam.github.io/mongo-drivers-benchmarks/

**Comment by gosubpl** [comment]
Also, official driver has Kerberos support, which ReactiveMongo is missing. Quite important to those in corporate environment.
@iozozturk would be great if you could create a PR, otherwise I will probably pick this up, as I have already once done a move reactivemongo -> official driver for the reaseons pointed above :)

**Comment by iozozturk** [comment]
I will propose a PR in a few days, I am struggling with the Java tests now. Thanks for reminding.

**Comment by stephennancekivell** [comment]
Hey @iozozturk. I've added a PR for a simple Sink. Theres not as much to it as with your Source, but at least it points beginners in the right direction.

It should merge well with yours, I've just C&P'd your config code.

**Comment by michalbogacz** [comment]
Hey, thanks for great work!
I have one additional idea: 
There is a new version of official mongo-scala-driver with support for case class conversion (http://mongodb.github.io/mongo-scala-driver/2.0/getting-started/quick-tour-case-classes/).
Since this connector is not released yet, can the implementation of source/sink be changed to generic? Not parametrized from beginning to org.mongodb.scala.Document?

This would remove the need to create custom converters of different types to the MongoDB Documents in the stream. Defining MongoDB CodecRegistry for conversion is much easier.
