### ISSUE TITLE
SSLHandshakeException happens during file upload to AWS S3 via Alpakka

### ISSUE THREAD

**Issue by Fruzenshtein** [akka/alpakka#1151]
I'm trying to setup an Alpakka S3 for files upload purpose. All code I run locally

alpakka s3 dependency:

```
...
"com.lightbend.akka" %% "akka-stream-alpakka-s3" % "0.20"
...
```

Here is application.conf:

```
akka.stream.alpakka.s3 {
  buffer = "memory"
  proxy {
    host = ""
    port = 8000
    secure = true
  }
  aws {
    credentials {
      provider = default
    }
  }
  path-style-access = false
  list-bucket-api-version = 2
}
```

File upload code example:

```
private val awsCredentials = new BasicAWSCredentials("my_key", "my_secret_key")
private val awsCredentialsProvider = new AWSStaticCredentialsProvider(awsCredentials)
private val regionProvider = new AwsRegionProvider { def getRegion: String = "us-east-1" }
private val settings = new S3Settings(MemoryBufferType, None, awsCredentialsProvider, regionProvider, false, None, ListBucketVersion2)
private val s3Client = new S3Client(settings)(system, materializer)

val fileSource = Source.fromFuture(ByteString("ololo blabla bla"))
val fileName = UUID.randomUUID().toString

val s3Sink: Sink[ByteString, Future[MultipartUploadResult]] = s3Client.multipartUpload("my_basket", fileName)

fileSource.runWith(s3Sink)
  .map { 
    result => println(s"${result.location}") 
  } recover {
    case ex: Exception =>  println(s"$ex")
  }
```

When I run this code I get:

_javax.net.ssl.SSLHandshakeException: General SSLEngine problem_

What can be a reason?

**Comment by ennru** [comment]
As I found out yesterday, you'll need to switch off SSL hostname checking:
```
akka {
  ssl-config {
    loose {
      disableHostnameVerification = true
    }
  }
}
```

**Comment by Fruzenshtein** [comment]
@ennru should I do this for under `akka` configs or `akka.stream.alpakka.s3`?

**Comment by jrudolph** [comment]
Turning off TLS hostname verification makes TLS far less secure, so it should only be a last resort workaround.

In my tests, the problems seems to be that for buckets that contains dots, Alpakka S3 tries to access the bucket through

https://abc.def.s3-eu-central-1.amazonaws.com/...

This also fails in the browser because Amazon delivers a wildcard certificate for `*.s3-eu-central-1.amazonaws.com` which doesn't seem to work for sub-sub-domains of s3 (any more? `openssl s_client` seems to accept it...)

The solution for now is not to use dotted bucket names. A final solution could be to access the bucket not through the subdomain but through

https://s3-eu-central-1.amazonaws.com/abc.def/...

which should work in any case.

**Comment by jrudolph** [comment]
Turns out, this has already been documented and implemented:

https://github.com/akka/alpakka/blob/96fbc9238be6a0c2fca8ffc686c3880c4d191ef2/s3/src/main/resources/reference.conf#L71-L76

So, the solution is to turn on `path-style-access` in configuration.

**Comment by Fruzenshtein** [comment]
@jrudolph thanks

Dots in the basket name really may cause this issue!

**Comment by jrudolph** [comment]
Maybe add a warning note on https://developer.lightbend.com/docs/alpakka/current/s3.html as well, that this can be an issue. Or maybe even better automatically fall back to path-style-access for dotted domains...

**Comment by ennru** [comment]
I created an issue to default to path-style access instead.
Closing this discussion.
