### ISSUE TITLE
Elasticsearch: Use of _version generates deprecation warnings for ES>=6

### ISSUE THREAD

**Issue by semafor** [akka/alpakka#1232]
_version and other related fields have been deprecated and will be removed in elasticsearch v7.

Migrating to a higher level client library would "permanently" fix this, but maybe there's rationale for keeping the low level client around.

Reproduce:
Index/Update docs in ES>=6

What do I expect:
No deprecation warnings/the ability to bump a higher level ES client to fix these errors

What happened instead:
_version is hard coded throughout the library, so there's no real way to upgrade to ES7 and keep using this library.

**Comment by ennru** [comment]
Thank you for reporting this. Elasticsearch is quite fast-paced on their JSON API, we should add a warning to the docs.
I believe the choice for the client implementation using raw JSON was made to achieve non-blocking API calls, does the ES client library offer that nowadays?

**Comment by takezoe** [comment]
> I believe the choice for the client implementation using raw JSON was made to achieve non-blocking API calls, does the ES client library offer that nowadays?

Official Elasticsearch client for REST API required raw JSON handling at that moment, but now a high-level client which can handle request and response as typed models is available. It may be possible to replace the current Alpakka implementation with the high-level client.

**Comment by Fs02** [comment]
I'm interested in replacing the client library with high level client, as it also open the possibility to remove `spray-json` from dependency (which i need because i'm using circe).

I've experimented some change using @takezoe original repository [here](https://github.com/Fs02/akka-stream-elasticsearch), I can try to modify and update current alpakka implementation if it allowed

**Comment by DJLemkes** [comment]
@Fs02 your work looks promising. Did you ever make a PR out of this?

I'm using Circe as well so I'd love to bring that into my flow instead of Spray. 

Besides, I'm also getting the `Specifying types in bulk requests is deprecated` warnings when using ES version > 7. This is due to the [`_type`](https://github.com/akka/alpakka/blob/44feb05e666dbfc2baa203822aff6ba28220b428/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala#L144) field being sent by the current implementation.

If I'm not mistaken, this would be fixed when the high-level REST client is used instead of the current one. Only problem could be that Elastic recommends to keep cluster version and high-level client version in [sync with each other](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.2/java-rest-high-compatibility.html).

**Comment by ennru** [comment]
Hi Alpakka Elasticsearch users,

It might be a good idea to investigate the switch to the high-level Java API now that we are getting closer to go for Alpakka 2.0. The drawback might be that the high-level API client is required to be in-sync with the Elasticsearch server version.

BTW: The conversion of user data to JSON became a bit more pluggable recently with the `StringMessageWriter`.

**Comment by ennru** [comment]
I talked to an Elasticsearch expert today, they recommended against the Java API as it is Elasticsearch server dependent. Instead, they recommended introducing some kind of version awareness which would create the JSON that the server understands. Some of the features Alpakka Elasticsearch uses will not be available in later Elasticsearch versions.

**Comment by ennru** [comment]
We just merged #2052 so that we can implement different REST messages according to the ES version.
Would be great if ES users can help and implement support for ES 6 and ES 7.

**Comment by r-glyde** [comment]
I've had a go at adding support for V7 in #2277 (the build is failing at the moment but I'll try and sort that out this evening).

Probably a bit late to offer a temporary solution to the original `_version` issue but with the existing API I think you should be able to use `withCustomMetadata` and pass the `version` field that way rather than using `withVersion`. Seems to work ok for me at the moment in some tests. Not ideal but might be good if anyone is still stuck until there is real support for version 7.

**Comment by ennru** [comment]
With #2277 users may now use ES 7 compatible REST calls.
