### ISSUE TITLE
S3: Use AWS SDK 2.0

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1342]
See #372

**Comment by gabfssilva** [comment]
I'm not sure this issue should be closed, since the PR #1905 is only removing the SDK 1.x dependencies and not really using SDK 2.x as the client, but rather keeping using Akka HTTP.

I think the confusion is cause we used SDK 1.x to reuse the domain classes from S3 api only, not for the client itself.

Though removing the SDK 1.x dependencies is a good thing, there should be a pattern and all AWS connectors should use the SDK 2.x as the client.

**Comment by ennru** [comment]
You're right, the focus was to not use AWS SDK 1.x anymore so this ticket was badly named. I'll rename it after the fact so it makes more sense.
