### ISSUE TITLE
FTP Connector: Add mv Operation

### ISSUE THREAD

**Issue by eharik** [akka/alpakka#155]
Add a function to the dsl to move files on an FTP (or FTPS, SFTP) server.

**Comment by juanjovazquez** [comment]
@eharik Do you have any ideas about what semantic should be appropriate for this kind of operations?. Maybe a `Sink` that receives the file info and performs some kind of operation on the server as a result?.

**Comment by eharik** [comment]
@juanjovazquez that's what I was initially thinking as well.  However, in the past I've found libraries that provide a `Sink` to be less usable than those that provide a `Flow` since `Sink` is a terminal operation.  For example - what if I want to first move a file and then delete the initial file assuming the move was a success?  Could I do that if `mv` and `rm` were both a `Sink`?  I would imagine there is a way but not one that comes readily to mind. 

What about something along the lines of:

```
def mv(fromPath: Path, toPath: Path, settings: S): Flow[(Path, Path), (Path, Path), _]
def rm(fromPath: Path, settings: S): Flow[Path, Path, _]
```

One concern, IMO, is that these operations really have no effect for a client - just the FTP server.  So, in that sense, a `Sink` is more intuitive.  I just find from experience that I usually want to then take additional action (like updating an event journal, for example).

**Comment by johanandren** [comment]
Wouldn't it be better to have a few concrete higher level use cases covered by for example FTP source - read files and remove them, read files and move them etc. than to try to model everything a FTP client can do as a stream? If arbitrary manipulation over ftp is what you want to do, then maybe streams is not the right abstraction.

**Comment by eharik** [comment]
When you've got a hammer...

Yes, @johanandren, I think your suggestion makes sense and seems more in-line with how Camel approaches FTP file transfers.

**Comment by svezfaz** [comment]
@juanjovazquez @johanandren @eharik 
What if we augment the `IOResult` we get back from the streaming source/sink to be able to perform - e.g. - mv or rm operations? Something along the lines of
```
trait FtpFileHandle {
  val result: IOResult

  def move(path: String): Done
  def remove(): Done
}
```
so that you could do something like
```
      Source.single(ByteString("hello"))
        .toMat(Sftp.toPath("filename", settings))(Keep.right)
        .mapMaterializedValue(_.map(_.move("anotherFilename")))
        .run()
```
For the purpose we could embed the FtpClient inside the handle. There are probably better way to implement this, haven't really thought about that in depth. However I think the semantics of operating on the materialized `Future` are the correct way to go about this. WDYT?

**Comment by eharik** [comment]
I guess the basic question is do we want to add general FTP client ops to the API at all? (restating @johanandren 's point above).  Could the same be accomplished by calling the client ops on the materialized value after the streaming work is done?  Downside there is one now has to work with both Alpakka streams and the FTP client directly.

Regarding the specific API suggestion - it implies a "fire and forget" model, right?  Both `move` and `remove` can fail but that isn't reflected in the return type.  Would it be worth having the return type as a `Future[Done]` and call `flatMap` on the materialized result?

**Comment by juanjovazquez** [comment]
I definitely do like the idea of having some post-processing operations as `move`, `remove` and maybe `copy`. That way, we make easier the most useful operations to the user. Otherwise, we force him to instantiate an FTP client and all that jazz.

**Comment by carstenlenz** [comment]
Interesting discussion. As we evaluate Alpakka for our integration needs (to replace an existing integration tool) I immediately missed this feature in some way because this is a common behaviour for integration tools. 

Having used Akka Streams for some weeks now having a seperate "building block" for moving and deleting seems more natural for Akka Stream / Alpakka. On the other side having it built into a specialised `Source` as a combined retrieve and move / delete operation would be more end user friendly.

**Comment by jaapterwoerds** [comment]
I often have to deal with legacy systems which use SFTP as means of exchanging of messages. The semantics are that one file is one message. For these uses cases I want to mark the file as processed, either by removing it or removing it. 

If we add combined operations like read/remove and read/move as suggested above, how can I be sure that message are always processed?

Why not model the move / delete as a sink, for example like this:
```
def move(
      destinationPath: FtpFile => String,
      connectionSettings: S
  ): Sink[FtpFile, Future[IOResult]]

def remove(
      connectionSettings: S
  ): Sink[FtpFile, Future[IOResult]]
```

**Comment by jaapterwoerds** [comment]
I created a PR to implement mv / rm as a Sink: https://github.com/akka/alpakka/pull/641
