### ISSUE TITLE
SQS connector produces plenty of empty receives

### ISSUE THREAD

**Issue by gipeshka** [akka/alpakka#1740]
### Versions used 

1.0.1

Akka version: 

2.5.17

### Expected Behavior

As of version 1.0.0-M1 the behaviour of Alpakka sqs connector was to reduce the amount of requests sent to SQS in case there is an empty receive.

### Actual Behavior

Current implementation doesn't scale down the consumption on empty receives. Users switching to the new version might experience huge increase in AWS costs.

**Comment by ennru** [comment]
Thank you for reporting, that seems to have been lost in the SQS make-over.

**Comment by RustedBones** [comment]
In `1.0.0-M1`, the concurrency was decreased to 1 in case of empty receive. See [here](https://github.com/akka/alpakka/blob/960f49a1a654b80b38ee83f2a9677785a8df17e4/sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsSourceStage.scala#L82).

Now, the [`mapConcat`](https://github.com/akka/alpakka/blob/c137fcf1c174e0685546d14699f9bdca876413b4/sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala#L48) from the source will request messages from upstream in a greedy fashion. Instead of having 1 request per `waitTimeSeconds`, we will have `parallelRequests` in the same duration.

Adding a `throtle` stage above the `mapConcat`  that delays in case of empty response could maybe solve the issue.

**Comment by RustedBones** [comment]
@gipeshka did you set a `parallelRequests` > 1 ?

**Comment by gipeshka** [comment]
@RustedBones yes, it's set to about 30

**Comment by RustedBones** [comment]
@gabfssilva was partially right in his [comment](https://github.com/akka/alpakka/issues/1588#issuecomment-476070078).

> And now I see that there's kind of a problem with the approach I took by using pre-defined stages since `mapAsync` is executed eagerly and more messages are getting fetched than the buffer predefined. (even with your fix, @RustedBones, tho it fixes the non stopping polling)
> 
> Also, since the `mapAsync` is stateless, it cannot know how many messages it can poll from SQS based on the size of the current buffer, it always fetches based on `maxBatchSize` setting. So, even if the buffer is set to 20 and the stream has 19 elements, it'll try to fetch more 10 messages, which is not what should happen.
> 
> I think the problem occurs because of `mapAsync` + `mapConcat(identity)` + `buffer(settings.maxBufferSize, OverflowStrategy.backpressure)` all together. Even using `mapAsync(1)` it sends more requests than expected. What I think is: while the buffer is not full, `mapAsync` keeps being called. This way more messages are being grabbed than the `maxBufferSize` setting.
> 
> Should I create an issue to talk specifically about it?

`mapAsync` is not started if there are no request from downstream. But when it receives one, it fires as much async operations as possible until the request is fulfilled. So `mapAsync(1)` is OK in our case . However, setting a higher parallelism will introduce unwanted behaviors:

- Fire too many `receiveMessage` requests sent, especially when the queue is empty: The futures are completed late due to the `waitTime`.
- In case of FIFO, the `mapAsync` doesn't guarantee that AWS SQS will process the requests in the same order they were sent. We may then process messages out of order in the stream. In the same way, if `closeOnEmptyReceive` is set, we may stop the stream without processing messages in other pending operations.

I don't see any solution other that implementing our own `GraphStage` as it used to be. And even though, to properly support the FIFO requirement, parallelism MUST be 1.

**Comment by ennru** [comment]
This is fixed with #1743.

**Comment by gipeshka** [comment]
@RustedBones you're right, in case of FIFO the configuration has to be very strict.

I'd say that cases of slow acknowledgment of SQS messages are quite tricky.

My case is not a FIFO, I process a lot of messages very fast, however when implementing a test for `SQSSOurce` I also found it strange that we execute that many requests to the external service, see https://github.com/akka/alpakka/blob/master/sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala#L49

MapAsync + smallest buffer can also lead to bugs we've faced on another project where the processing service is slow, eg:
- The visibility timeout in SQS is 30 seconds
- The service processes a message in about 3 seconds, no parallelism (10 messages = 30 seconds)
- The service starts processing messages, expecting only 10 messages to be present, however there are 30 requested from SQS.
- The service processes first 10 messages, when processing the message №11 `MapAsync` will execute a call to SQS and will receive the messages №11 to №20 (visibility timeout expired), that are about to be read.

This behaviour is not quite obvious, I think the spec for SQSSource should help understanding it better.

**Comment by ennru** [comment]
Thank you for discussing this further.
Could this be turned into better documentation of the settings, or does anybody see a "technical" solution?

**Comment by gipeshka** [comment]
@ennru @RustedBones 
I am not sure how often is the FIFO case used, however with custom stages I believe FIFO case can be solved using a `1`-parallelism async stage with lazy execution (execute call only when pulled) with no buffer.

That means however completely different source implementation for FIFO, maybe additional method on SQSSource object for such a case?

Anyway, I guess we can create a dedicated issue for this, WDYT?
