### ISSUE TITLE
Support other datatypes than String for JmsSink

### ISSUE THREAD

**Issue by eirirlar** [akka/alpakka#199]
As of now, the only API support for Jms Sinks is this:

```
val jmsTopicSink: Sink[String, NotUsed] = JmsSink(
  JmsSinkSettings(connectionFactory).withTopic("topic")
)
```

Other datatypes should be supported, at least the various message types in the Jms spec like TextMessage.

On that note, an API that exposes the JmsSession to the client should be implemented, so one could call i.e session.createTextMessage.

**Comment by eirirlar** [comment]
As a workaround for jms Messages, I created this for personal use.
´´´
package akka.stream.alpakka.jms

import javax.jms.{Message, MessageProducer}

import akka.NotUsed
import akka.stream.scaladsl.Sink
import akka.stream.stage.{GraphStage, GraphStageLogic, InHandler}
import akka.stream.{ActorAttributes, Attributes, Inlet, SinkShape}

object Jms {
  def sink(jmsSettings: JmsSinkSettings): Sink[Message, NotUsed] =
    Sink.fromGraph(new JmsMessageSinkStage(jmsSettings))
}

final class JmsMessageSinkStage(settings: JmsSettings) extends GraphStage[SinkShape[Message]] {

  private val in = Inlet[Message]("JmsSink.in")

  override def shape: SinkShape[Message] = SinkShape.of(in)

  override protected def initialAttributes: Attributes =
    ActorAttributes.dispatcher("akka.stream.default-blocking-io-dispatcher")

  override def createLogic(inheritedAttributes: Attributes): GraphStageLogic =
    new GraphStageLogic(shape) with JmsConnector {

      private var jmsProducer: MessageProducer = _

      override private[jms] def jmsSettings = settings

      override def preStart(): Unit = {
        jmsSession = openSession()
        jmsProducer = jmsSession.session.createProducer(jmsSession.destination)
        pull(in)
      }

      setHandler(in,
        new InHandler {
          override def onPush(): Unit = {
            val elem = grab(in)
            jmsProducer.send(elem)
            pull(in)
          }
        })

      override def postStop(): Unit =
        Option(jmsSession).foreach(_.closeSession())
    }
}
´´´

**Comment by johanandren** [comment]
This has been discussed in #149, I think it will be in the PR for that.

**Comment by d2e8f9** [comment]
Please take a look at the commit above and let me know if something is missing. The JmsSink and JmsSource supports now Byte-, Map- and ObjectMessages according to the Jms spec. 

Therefore  a JmsMessage trait is introduced and refactored out to a separate file. 
The logic to create and populate the Jms messages is still inside the JmsSinkStage. I would move it from there to another place, but I don't know which direction to go... 

- Passing the Java.jms.Session to the JmsMessages,so that this classes could create their javax message representation 

or    

-  introduce a MessageFactory (or something like that)

**Comment by d2e8f9** [comment]
Please see #430
