### ISSUE TITLE
google cloud pubsub

### ISSUE THREAD

**Issue by stephennancekivell** [akka/alpakka#208]
Hi, I can add a connector for GCE pub sub. I have seen other akka streams connectors, however they are using blocking APIs. One could be built on top of akka-http, we just need to add a bit of logic for OAuth on JWT tokens.

https://cloud.google.com/pubsub/docs/overview

**Comment by johanandren** [comment]
@saturnism was looking into this a bit when I met him a couple of weeks ago, maybe he has some input?

**Comment by stephennancekivell** [comment]
Thanks @johanandren, Ill hold off if @saturism has already started.

**Comment by patriknw** [comment]
very interesting connector!

**Comment by saturnism** [comment]
awesome! looks like it's going to the restful api directly, which is great right now.

fyi, there is a streaming/async client: https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/spi/v1

It may not fit this use case at the moment due to back-pressure handling (or perhaps the lack of)!

would love to get your feedback on this lib when it's switched to use full gRPC streaming.

in the mean time, this looks fantastic!
