### ISSUE TITLE
Jackson Databind unnecessary dependencies

### ISSUE THREAD

**Issue by smiklos** [akka/alpakka#2372]
Dear devs,

I know I should have asked on the provided page but I'm tired and I hope my questions gets answered here as well.

It's simple: Why does all project in Alpakka depend on Jackson Databind?  The dependecy declaration even mentions that it should be aligned with akka. But akka, akka-streams and akka-http doesn't depend on jackson afaik. 

The only usage I find in this repo is for Elasticsearch. 
This caused me a huge headache as for aws, the sdk v2 already provides jackson dependencies, so there's no need to mention them again especially when they are not even used...

**Comment by ennru** [comment]
Alpakka overwrites the Jackson Databind dependency to 2.10.4 for the AWS connectors to make sure users end up with the later patch version than used by the AWS client libraries.
This is important because Jackson fixes some security issues in these patch releases.

Akka uses Jackson CBOR for its communication within a cluster, that is why Alpakka needs to align with the Jackson minor version in Akka.

How is this causing a headache for you?

**Comment by smiklos** [comment]
By saying 'Akka' which project are you talking about? Looking at the compile time deps for Akka Actor/Stream/Http, I can't see any databind dependencies there. This project doesn't depend on akka cluster so there should be no need to enforce a higher version. 
My problem is that this version collides with some old lib we use and while I did exclude sqs I didn't realize that I have to double exclude jackson. (I needed to exclude sqs to use an older version that ships with an old databind version).

**Comment by ennru** [comment]
Akka doesn't depend on Jackson Databind, but other Jackson modules.
We up the dependency which the AWS client brings in to avoid the security warnings scanners detect.
(As you see, #2373 ups Jackson to 2.10.5 and this dependency overwrite is intentional.)

**Comment by ennru** [comment]
The current AWS SDK libraries don't depend on Jackson anymore. I opened #2806.
