### ISSUE TITLE
Bump Google Cloud Storage to Akka Http 10.2

### ISSUE THREAD

**Issue by tonicebrian** [akka/alpakka#2757]
### Short description

Most of the tools I use (circe, akka-http, code generators...) are using akka-http 10.2. Because of the binary incompatibility betwen 10.1 and 10.2 I cannot use Alpakka for Google Cloud Storage since it relies on 10.1. I've seen that you are already compiling with 10.2 but only on Travis.

What else needs to happen to bump the version of akka-http or where could I find a released version of Alpakka Cloud Storage with such version?

**Comment by janjaali** [comment]
It's not only about Google-Cloud-Storage, at least AWS S3 and AWS DynamoDB are affected as well and I am certainly sure there are also other artifacts which are waiting for an akka-http version update ;)

**Comment by janjaali** [comment]
#2650

**Comment by ennru** [comment]
You can use both Akka HTTP 10.1 and 10.2 with Alpakka 3.0 connectors. To verify that CI runs the tests even with Akka HTTP 10.2.

We don't have a lot of time to spend on Alpakka, but we're pushing things forward so that we can bake Alpakka 4.0 very soon. That will include the default use of Akka HTTP 10.2.

**Comment by ennru** [comment]
Alpakka 5.0.0 uses Akka HTTP 10.4.
