### ISSUE TITLE
SQS - Batch Send and Delete Operations

### ISSUE THREAD

**Issue by mehmetgunturkun** [akka/alpakka#383]
Hi,

As far as I can see, there is no support for batch sending and deleting messages over SQS. I thought it might be useful.

Any ideas, interest?

**Comment by aserrallerios** [comment]
Yes, this is a must. We are not using alpakka's SQS because of this issue. If your throughput needs are above average, you'll get a ton of server errors if you're not using batches of 10 (the max batch size).

I'd just change the internal SQS stages to use `Seq[Message]` instead of `Message` and put a `batch` size 10 before them. The changes would be trivial and the interface would remain unchanged. That's how we do it and it's working pretty well.

WDYT? I can prepare a PR if community likes the proposed solution.

**Comment by mehmetgunturkun** [comment]
Hi @aserrallerios thanks for your offer but I already have a working implementation and going to create a PR. However, I would love to get a review from you when I send since it meets your needs.
