### ISSUE TITLE
FTP connector

### ISSUE THREAD

**Issue by ktoso** [akka/alpakka#4]
To track the in progress PR: https://github.com/akka/alpakka/pull/3

**Comment by juanjovazquez** [comment]
After the first steps implementing the FTP connector I'd need your help / opinion in order to come up with a decent API for end users and also to clarify what would be the scope of the component in terms of offered capabilities.

As I see it, we need to solve these four typical scenarios : browsing, retrieving, creating and deleting/moving, always following the reactive streams philosophy of course.  The browsing part is what has been tackled so far, and it's in fact the default option via the FtpSource factory. This needs to be changed to accommodate the other features.

Having said that, I can think of a couple of alternatives. First, having an unique façade and different factory-like methods. Something like this:

    Ftp.list(basePath: String, recursive: Bool, ....)
    Ftp.retrieveFromPath(basePath: String, ....)
    Ftp.putOnPath(targetPath: String, ....)
    Ftp.removePath(targetPath: String, ...)
    Ftp.moveFromToPath(origin: Path, destination: Path)

And the same for `Ftps` and `SFtp`. These factory methods would create different kinds of sources according to what needs to be done.

The other alternative could be to have different façades as `FtpBrowser` for browsing, `FtpIO` for retrieving and creation and so forth.

I've had a look at how Camel is dealing with this and it's hard to draw conclusions  as Camel's semantics is quite different from Akka Streams. For instance, Camel let you retrieve all files on some directory whereas I feel more natural in Akka Streams to generate a stream of file descriptors and then retrieve them one by one asynchronously.

WDYT?

/cc @2m @ktoso @patriknw

**Comment by patriknw** [comment]
I like the factory methods as you show in the example
