### ISSUE TITLE
CSV parser should be configurable with an upper limit

### ISSUE THREAD

**Issue by johanandren** [akka/alpakka#509]
Something like `Framing.delimiter(..., maximumFrameLength = 4096)` to protect against someone feeding it text without delimiters potentially filling the heap.

There is an example test case in #502

**Comment by Voltir** [comment]
That is one way it kind of could be done.. but I don't believe it is the best way. Or rather, if you really want to do everything at the byte level... fine, i guess, but I think there is, in addition, a need for a simpler API. In particular, something like `CSV.line: Flow[String, List[String]] - and its configured using `Char` instead of `Byte`.

I think the current API, as exposed by lineScanner, is actually too low level and conflates too many concerns. First, framing - we already have a utility to do framing and I want to compose with it (as demonstrated in the PR). Second is using `ByteString` - in addition to doing the job of parsing csv's correctly, using bytestring also requires dealing with encoding issues - utf8 is not latin1 or utf16. It kind of all works because the most common bytes in English text all overlap with ascii, but there are problems - maybe my delimiter in utf8 isn't representable as a single byte (forgetting that utf8 is actually a variable with encoding is really common...)

So.. let me compose in whatever `Bytestring` -> `String` decoding I want and then let me extract out the fields line by line with something like `CSV.line`.
