### ISSUE TITLE
S3 bucket using _ causes issues

### ISSUE THREAD

**Issue by calvinlfer** [akka/alpakka#511]
I have a bucket named `calvin_example`, this causes the Alpakka S3 connector to have trouble
```scala
implicit val system: ActorSystem = ActorSystem("gatling-experiment")
implicit val mat: ActorMaterializer = ActorMaterializer()
val s3Client = S3Client()
s3Client.listBucket("calvin_example", None).to(Sink.foreach(println)).run()
```

Results in 
```log
[ERROR] [10/05/2017 23:40:59.268] [akka://experiment/user/StreamSupervisor-1/flow-3-0-unknown-operation] Contains non-LDH ASCII characters
```

However, any other bucket I have (like `calvin-ok`) works correctly. I have also checked to make sure the permissions are accessible by the role/user I am using. Is this intended behaviour? Am I supposed to use `prefix` in this case?

Thanks

**Comment by Guidoooch** [comment]
The issue is that the bucket list name must abide the DNS convention (only LDH characters and single dots) when used with `path-style-access` is set to false.

The property's full path is: `aws.akka.stream.alpakka.s3.path-style-access`

You should set this property to true if you want to use non-LDH characters, but the advice from amazon is to stick with the DNS naming convention.

More on the topic here: [AWS bucket restrictions](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html).

**Comment by Guidoooch** [comment]
In this pull request we improved the error message thrown in case of non-LDH characters in the bucket name and path-style-access set to false.

**Comment by calvinlfer** [comment]
Thanks a lot guys! 👍
