### ISSUE TITLE
SQS connector does not complete.

### ISSUE THREAD

**Issue by katainaka0503** [akka/alpakka#513]
## Steps to reproduce

1. Execute SQS connector with local ElasticMQ
2. Push Message to ElasticMQ
3. Run below code and wait a while.
```scala
SqsSource(queueUrl).map { message =>
  val action =
    if (ThreadLocalRandom.current().nextBoolean()) Delete()
      else Ignore()
  println(message)
  (message, action)
}.runWith(SqsAckSink(queueUrl)).onComplete(println)
```
4. Stop ElasticMQ. SQS connector sometimes does not complete Future of it's materialized value.

I think this is a bug because If I change the arg of `.map()` , `Future[Done]` of the materialized value properly complete with exception.

**Comment by kag0** [comment]
What exception are you expecting to see?
By design SQS streams do not complete unless you've done something to indicate when they end. From [the documentation](http://developer.lightbend.com/docs/alpakka/current/sqs.html#stream-messages-from-a-sqs-queue):
> ``` scala
> SqsSource(queue, sqsSourceSettings).take(100).runWith(Sink.seq).map(_ should have size 100)
> ```
> As you have seen we take the first 100 elements from the stream. The reason for this is, that reading messages from SQS queues never finishes because there is no direct way to determine the end of a queue.

Also relevant: depending on your supervision strategy, exceptions in stages of your stream may not cause the stream to fail (the message will just be dropped instead).

**Comment by RustedBones** [comment]
This is actually related to the use of `Ignore` as a message action.

The `SqsAckFlowStage` is incrementing an in flight counter on all incoming messages and decrementing on getting the response from AWS SQS.

However, `Ignore` does not fire any request against SQS, so the counter wasn't decremented. The `checkForCompletion` method is never completing the stage because the counter value stays positive.
