### ISSUE TITLE
File Rotation Sink: dangerous time-based rolling example

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#584]
Just had a closer look at the File Rotation Sink and the proposed usage examples:
* The size-based rotation example contains a `println`
* The time-based rotation will roll every millisecond (and `LocalDateTime` might be enough) 

These two rolling functions could become a part of the standard API.

@tg44 Would you like to propose an update? (I could fix the docs, if you don't have a chance to get at it.)

**Comment by tg44** [comment]
I'm not really understand the problem here. These are test/example code, so I assume who is trying this out will read it before.
If I give a bigger roll period (for ex 1 sec or 1 min) I need to give a throttled source, and it will need significantly more time if you just want to demonstrate it. (Not mentioned the more complex example.) 
The println could be removed...

The other (add to the standard API) request was my first try, bcs I wanted a simple time based rotator. I think this api with the 2 example code is more useful and extendable then for ex 'a basedir, a cron expression and a name generation pattern' as parameters.
We can make default implementations if those are cleaner or easier. If you have something in mind you can add them, but I let this idea go when I realized the naming pattern problem :)


So summarized; I see why these can be problems, just not sure these really are in this context. But if you think it will make the lib better/more usable/clearer just start a new PR :D

**Comment by ennru** [comment]
Thank you for your reply.
I'd prefer the examples to be 'ready for real use'. I'll give it a try.

**Comment by tg44** [comment]
Okay, then fell free to modify them :) If you need any help just post it here or find me on gitter.
