### ISSUE TITLE
Direct logging to files in tests

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#610]
The logging of the used libraries hides test failures in the build logs. 
By adding proper dependencies and configurations this logging can be removed.

**Comment by raboof** [comment]
Good one! Sometimes the logging is useful though... but indeed we should suppress 'expected' warnings (in configuration or with `EventFilter`) and it'd be great to collect the logs in a more controlled way instead of interspersed with other output. As a hack searching for `***` in the logging works for me, but that's not great :).

**Comment by ennru** [comment]
Ok, I'll direct all logging to files instead. 
Is there a way to make those accessible in Travis?

**Comment by raboof** [comment]
Not really AFAIK. I guess we could upload them somewhere or just 'cat' them into the build output after running the tests.
