### ISSUE TITLE
No support for SQS Fifo queue?

### ISSUE THREAD

**Issue by hejfelix** [akka/alpakka#625]
When I try to use a FIFO queue, I get the following error:

> The request must contain the parameter MessageGroupId. (Service: AmazonSQS; Status Code: 400; Error Code: MissingParameter; Request ID: 628341eb-8a17-5841-a110-1374cae6b8a1)

If I simply change the `sqsEndpoint` to a non-fifo SQS queue, everything works as expected. I don't see how to even pass the message group ID, so it looks like it is unsupported at the moment, is this correct?

**Comment by awsfanatic** [comment]
Could you provide the code to reproduce the problem? The doc says:

> However, beware that AmazonSQSBufferedAsyncClient does not support FIFO Queues. See documentation for client-side buffering.
https://developer.lightbend.com/docs/alpakka/current/sqs.html

> The Amazon SQS Buffered Asynchronous Client doesn't currently support FIFO queues.
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-client-side-buffering-request-batching.html

**Comment by hejfelix** [comment]
I believe this was on 0.14 which does not contain those sections that you mention: https://developer.lightbend.com/docs/alpakka/0.14/sqs.html 

Looks like support may have been added for FIFO since then. Since my use case never required FIFO, I went with the non-FIFO version. I doubt I will have time to try it out, but if support has indeed been added, please close this ticket 👍

**Comment by RustedBones** [comment]
FIFO is not supported for batch mode at the moment because the `getMessageGroupId` and the `getMessageDeduplicationId` are not copied to the `SendMessageBatchRequestEntry`

**Comment by martyphee** [comment]
@RustedBones any idea when this will be supported?

**Comment by RustedBones** [comment]
The last comment is deprecated.
After refactoring to new AWS client in #1450, the fields have been set and extracted from the batch result.

Unfortunately, the outpout type of the `SqsPublishFlow.batch` is wrong:
It has been set to `List[SqsPublishResult[SendMessageBatchResponse]]` instead of `List[SqsPublishResult[SendMessageBatchResultEntry]]`

Indeed, `SqsPublishResult` contains the `FifoMessageIdentifiers` which are associated with the messages, and not with the batch request operation.

That makes the API inconsistent.

**Comment by RustedBones** [comment]
This last comment is deprecated.
The feature has been implemented in #1450 when migrating to AWS 2.0 sdk.

Unfortunately, the API from the [SqsPublishFlow.grouped] is a bit inconsistent: The output type is a `List[SqsPublishResult[SendMessageBatchResponse]]`, this means that for each message in the batch, they will contain the same metadata. There is then no way to access the actual metadata entry for the individual message because we do not have access to the message id used during the batch operation.

I would suggest to change the output type to `List[SqsPublishResult[SendMessageBatchResultEntry]]`

This also applies for the `SqsAckResult`
