### ISSUE TITLE
[mqtt] report connection error

### ISSUE THREAD

**Issue by aitorhh** [akka/alpakka#635]
Hi,

I am really missing the error reporting in the mqtt connector. In my application, I have no clue if the connector is in "connected" state or not. Is there any way that the streams stop working and sends an exception to its supervisor? For example, I current handle other exception in my stream with, by defining the following:

```
  val decider: Supervision.Decider = {
    case e =>
      logger.error(s"Error processing message: $e. Stopping")
      Supervision.Stop
  }
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer(
    ActorMaterializerSettings(system)
      .withSupervisionStrategy(decider)
    )
```

Currently, I am completely blind on error cases with mqtt. I hope there is already a solution that I haven't figured it out yet.

Thanks!

**Comment by juanjoDiaz** [comment]
Hi Aitor,
Can you add code example of what you would expect?
AFAIK the MQTT connector fails its stage if the connection drops.

**Comment by juanjoDiaz** [comment]
The error missing on two consumers with the same clientId is an issues with most MQTT libraries (they don't report when a client is kicked out). I'm following up the issue in https://github.com/eclipse/paho.mqtt.java/issues/461 and I'll fix it in alpakka as soon as it is fixed in Paho.

Automatic reconnect is not enabled by default. It has to be enabled.

Otherwise, maybe I'm misunderstanding but I don't think that an exception should be thrown from the stream. It just fails the stage and all the stages upstream or downstream are failed. Are you expecting something else?

**Comment by aitorhh** [comment]
Thanks for the information.

When you say that the stream fails, how can the user/system be notified of
the failure? That's actually what I'm after. Seems that I am missing
something that already exists.

In the previous examples, the application just remains running without any
message, log or anything that indicates the error.

**Comment by aitorhh** [comment]
Great to see these features added. I close the issue. Thanks!
