### ISSUE TITLE
Skip Sinks in Alpakka?

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#725]
We seem to add code for Sinks which just complement a Flow with an ignore Sink. This is the same thing as ignoring a method return value, which should be a concious decision.

1) Would it be better to just focus on Sources and Flows in Alpakka?
2) Should we remove existing Sinks which just add the ignore Sink?

**Comment by aserrallerios** [comment]
My 2 cents:

1. Yes
2. Yes

I cannot think in any scenario where I'd *need* usless Sinks sit in the same place as the Flows.

You can even define an implicit class for Sources & Flows with a `def ignore` method.

```
someSource.via(something).ignore
someFlow.via(otherFlow).ignore
```

**Comment by juanjoDiaz** [comment]
Here is my view:

First of all, I think that sources, flows and sinks are all equally important. So if alpakka drops sinks, there will be a need for another library for sinks.

I agree that many sinks are just `via(something).ignore`
However, there might be also sources that are `Source.maybe.via(something)`

The MQTT connector is an example of this. There is just one flow stage and the source, the flow and the sink are built on top of it. And I'm sure that the AMQP and other connectors could be implemented in the same way.

In any case, I think that those are implementation details and the user shouldn't care about them.
The users should care about the API they can consume in their applications.
As a user, I think that's important to have an API for source, for flow and for sink that are reliable, easy to use and well documented. Regardless of how they are implemented (that's the whole point of using a library vs building your own).

So I would vote NO for removing sinks or shifting the focus towards sources & flows.
What I would suggest is to focus on the APIs so they are simple, usable and well documented in both Scala and Java. The rest, as said, is just implementations details.

**Comment by aserrallerios** [comment]
Ok to the "implementation details" argument.

* But, what if ALL Sinks are just flow.ignore? If so, I think users should know it.
* How do we keep under control the API right now? Imagine that you need to name a xxxPublisher, what API would you provide to the end user?
    * xxxPublisher (which is just the Flow)
    * xxxPublisherFlow
    * xxxPublisher + xxxPublisherSkink
    * xxxPublisherFlow + xxxPublisherSkink
    * xxxFlow + xxxSkink
    * ???

Whatever we chose, it should be consistent everywhere and a crystal clear rule for contributors.

**Comment by sourcekick** [comment]
I think it would be cool and helpful to make it mandatory to provide at least one `Flow` and add/keep a `Sink` optionally, just for convenience.

**Comment by sourcekick** [comment]
Except for cases where only one or more `Source`s are applicable, where there cannot be a producing `Flow` nor `Sink`, where the connected technology can only provide data/elements, but not accept them.

**Comment by juanjoDiaz** [comment]
What I read from @sourcekick comments is "Each case is a bit different. Some connectors might have only source, others only flow, others only sinks and others a combinations of the above". Which was exactly my point above.

That also answer @aserrallerios question. The API can't be completely standard across connectors because all of them might be very different. (Same thing happens with #104). I think that we just need to make sure that the API for each connector is solid and easy to use. And the APIs between similar connectors are as similar as possible (let's say message queues connectors, the connectors for dbs that are very similar, etc).

I see Alpakka as a set of miniprojects (one per connector) with a common goal, connecting system using streams. I think that it's good since having all the connector together make sure to get ideas and import them from one connector to another or add new connectors. which would be more different if we would have 10s of repos. but we shouldn't consider it as a single project imho.

**Comment by aserrallerios** [comment]
"Some connectors might have only source, others only flow, **others only sinks** and others a combinations of the above"

Can you give an example?

**Comment by ennru** [comment]
I'm mostly interested to focus on a smaller API surface. 
I see connectors that contain flows also offering sinks created by connecting the flow to an ignore sink. This duplicates the amount of choices with doubtable benefit. 
For some use cases sinks are the perfect choice, but in many there is some useful information left after talking to the other connected technology - that is better handled by a flow.

**Comment by johanandren** [comment]
I think:
1. we should nudge contributors to make the outgoing implementations Flows rather than sinks as that is more flexible (there is some case-by-case consideration needed though)
1. it would also be nice if those Flows were consistent in how they allow for flowing (do they allow a pass-through value or just emit the result from the connected thing), not quite sure this is 100% possible
1. it is nice for newcomers if we have simple `NnnSink.sink(..): Sink[T, Future[Done]]` factories for the most common/most simple use cases, even if those are just composition of the flow and `Sink.ignore` (we do _not_ need to cover all possible parameters of the flows though), so that they can get started quickly and then move on to the more advanced/flexible flow usage when they realize they need it.

**Comment by aserrallerios** [comment]
Yeah, @ennru , that's the point 2. of your original message. To me, an smaller API is preferable to a rich API with too much boilerplate. Again, we can give other tools to the end user in order to ease alpakka usage which are less of a burden to maintain.

The controversy comes with the point 1.

From my experience, a Flow encourages reusage and Sinks don't. You need to materialize and run Sinks to get any feedback.

**Comment by ktoso** [comment]
> From my experience, Flows encourages reusage/composition and Sinks don't. 

Sure. Thus, implementations should often`Flow`s -- whenever possible.

Does it mean having Sinks provided is not useful? I strongly disagree. Ready to use, even if less composable Sinks *as additional API* are what gets people, beginners, interested -- "whoa, I made it work in 5 minutes!". And then they realise that they need more feedback, and can use the Flow API. Or maybe they don't, and the Sink is fine.

I would not want anyone to underestimate the benefit of "easy to get started", especially in Alpakka this aspect is tremendously important. And the mentioned maintanance burden really is not that high for just exposing such Sinks.

Also, some APIs are modeled as Sinks naturally, and that's fine as well. Just because they don't give nice feedback, no need to drop them and force into Flows.

> You need to materialize and run Sinks to get any feedback of what it's doing.

Same with **any** stream stage, any Flow, Sink, Source only give any feedback on what they're doing once materialized :-)

**Comment by aserrallerios** [comment]
Same with any stream stage, any Flow, Sink, Source only give any feedback on what they're doing once materialized :-)

I mean that a Flow can be flatMap'ed to build additional logic using existing Flows without materializing or running anything. If I'm not mistaken, that cannot be done with Sinks.

**Comment by ktoso** [comment]
What flatMap operation do you mean? If you mean changing elements (that's mapConcat), then yeah sure, a Sink does not do that, and it does not matter at all, it is the Sink, it's purpose is to terminate stuff and give a mat value back, not change elements. Changing elements would be done before a Sink.

In any case, it is not true that this is any different or "before materialization" -- these functions still would only execute and "give feedback" once materialized :)

Yes, Sinks are less composable.
Yes, they're absolutely valuable, esp. for people who just get started, and we want such people to enjoy using Alpakka as well, as that's how we grow adoption and users who "stay around for longer" (and realise they want a Flow perhaps).

**Comment by aserrallerios** [comment]
Yes, flatMap(Concat|Merge).

In a world of purely functional streams, sure. But a Flow can also be used to do some impure processing, for example publishing messages to an SQS queue, it's not just a transformation of input to output. In this particular scenario, a Sink would be strictly less useful than a Flow.

I agree on the ease of use is important, and I also agree on that some Flow just don't feel natural, and they're better modelled as Sinks (they are rare, though).

**Comment by ktoso** [comment]
I think we're in agreement ;-) Flows are more powerful, sure, but in order to make "try out Alpakka" *simple* for newcomers, yes we do want to provide Sinks as well, even if they're boring adaptations of their Flow counterparts.

If you mean mapping things on Flows, then for completeness this example should be included:

```
    // got my sink from a library!
    val sink: Sink[Any, Future[Done]] = Sink.ignore
    
    // I'm modifying things, and it's still a sink
    val stillASink: Sink[String, NotUsed] = Flow[String].map(_ + "!").to(sink)
```

The only difference is that Sinks don't have outputs. Which is perfectly fine in simple use cases, and also makes it simple for people to just try out. This is a tremendously important point -- for ease of "trying it out" of new users.

Do I argue that Sinks be the main thing? 
Absolutely not, Flows should, and if anything this should be the guideline given to authors: 

> (Dear library authors,) build Flows whenever possible, add Sinks when they seem to be useful. Always materialize something out of them (even if just a Future[Done]).

Which is also what @johanandren wrote above in: https://github.com/akka/alpakka/issues/725#issuecomment-360414448

Would this be a reasonable outcome from this ticket @ennru?

**Comment by ennru** [comment]
Yes. 
Going forward we should recommend contributors to focus on Flows and offer the most important variations as Sinks, as well - but not every combination the Flow might offer.
@johanandren and I have some ideas to revise the contribution instructions with this kind of hints.

**Comment by ktoso** [comment]
> Sinks, as well - but not every combination the Flow might offer.

That's good wording 👍 :)

**Comment by ennru** [comment]
Thanks everybody for you input on this. We can leave it here, and I close this discussion.
