### ISSUE TITLE
Contributor advice proposal

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#752]
I see the need to collect some advice how to build good Alpakka modules following the style that has evolved.
Please comment to get a common view of this. I'll create a PR with it when we get close to the next release.

Here is goes:

# Some advice for Alpakka contributors

## API design

Depending on the technology you integrate with Akka Streams and Alpakka you'll create Sources, Flows and Sinks.

When designing Sinks, please check if a Flow might be a better fit. Most other systems will give some kind of response which
could continue in a Flow. Sinks can easily created be attaching a Sink.ignore to the Flow. In case you want to offer 
Sinks based on Flows, focus on the most important cases and leave the more intricate variants just in the Flow API.

When designing Flows, consider adding an extra field to the in- and out-messages which is passed through. A common
use case we see, is committing a Kafka offset after passing data to another system.

### Settings

Most technologies will have a couple of configuration settings that will be needed for all Flows. Create case classes
collecting these settings instead of passing them in every method.

Create a default instance in the companion object with good defaults which can be updated via `copy` or `withXxxx` methods.

As Java can't use the `copy` methods, add `withXxxx` methods to specify certain fields in the settings instance. 

In case you see the need to support reading the settings from `Config`, offer a method taking the `Config` instance so
that the user can apply a proper namespace.
Refrain from using `akka.stream` as prefix, prefer `alpakka` as root namespace.

### Packages & Scoping

Use `private`, `private[connector]` and `final` extensively to limit the API surface. 

| Package                                  | Purpose
| -----------------------------------------|------------------------
| `akka.stream.alpakka.connector.javadsl`  | Java-only part of the API, normally factories for Sources, Flows and Sinks
| `akka.stream.alpakka.connector.scaladsl` | Scala-only part of the API, normally factories for Sources, Flows and Sinks
| `akka.stream.alpakka.connector`          | Shared API, eg. settings classes, implementation if thorowly made private
| `akka.stream.alpakka.connector.impl`     | Optional, implementation in separate package

### Regarding Java APIs

* Provide factory methods for Sources, Flows and Sinks in the `javadsl` package
* The Akka Stream Scala instances have a `.asJava` method to convert to the `akka.stream.javadsl` counterparts
* Let the Java API use Java standard types (`java.util.Optional`, `java.util.List`, ...) and convert using 
`JavaConverters` where needed
* Use the `akka.japi.Pair` class to return tuples
* Use `scala.compat.java8.FutureConverters` to translate Futures to `CompletionStage`s

## Graph stage checklist

* Keep mutable state within the `GraphStageLogic` only
* Open/close connections in `preStart` 
* Release resources in `postStop`
* Fail early on configuration errors

## Documentation

Create or complement the documentation in the `docs` module using [Paradox](https://github.com/lightbend/paradox) syntax.
Prepare code snippets to be integrated by Paradox in the tests.

Use ScalaDoc if you see the need to describe the API usage better than the naming does.

**Comment by juanjoDiaz** [comment]
Here are my 2 cents. Just added some stuff (the stuff in bold)

# Some advice for Alpakka contributors

## API design

### Settings

Most technologies will have a couple of configuration settings that will be needed for all Flows. Create case classes collecting these settings instead of passing them in every method.

Create a default instance in the companion object with good defaults which can be updated via copy or withXxxx methods.

As Java can't use the copy methods, add withXxxx methods to specify certain fields in the settings instance.

In case you see the need to support reading the settings from Config, offer a method taking the Config instance so that the user can apply a proper namespace.
Refrain from using akka.stream as prefix, prefer alpakka as root namespace.

### Public factory methods

Depending on the technology you integrate with Akka Streams and Alpakka you'll create Sources, Flows and Sinks.

**Regardless on how they are implemented make sure that you create the relevant Sources, Sinks and Flows APIs so they are simple and easy to use.**

### ~~Regarding~~ Java APIs

* Provide factory methods for Sources, Flows and Sinks in the `javadsl` package **wrapping all the methods in the Scala API**
* **Any class used by the connector that uses Scala specifics (Futures, etc.) should have it's counterpart and a implicit conversion class in the `javadsl` package**
* The Akka Stream Scala instances have a `.asJava` method to convert to the `akka.stream.javadsl` counterparts
* Let the Java API use Java standard types (`java.util.Optional`, `java.util.List`, ...) and convert using `JavaConverters` where needed
* Use the `akka.japi.Pair` class to return tuples
* Use `scala.compat.java8.FutureConverters` to translate Futures to `CompletionStages`


## Implementation details

### Packages & Scoping

Use `private`, `private[connector]` and `final` extensively to limit the API surface.

| Package        | Purpose           |
| ------------- |--------------:|
| akka.stream.alpakka.connector.javadsl      | Java-only part of the API, normally factories for Sources, Flows and Sinks |
| akka.stream.alpakka.connector.scaladsl     | Scala-only part of the API, normally factories for Sources, Flows and Sinks      |
| akka.stream.alpakka.connector | Shared API, eg. settings classes, implementation if thorowly made private      |
|akka.stream.alpakka.connector.impl      | Optional, implementation in separate package      |

### Graph stage checklist

* Keep mutable state within the `GraphStageLogic` only 
* Open ~~/close~~ connections in `preStart`
* Release resources in `postStop`
* Fail early on configuration errors
* **Avoid code that is:**
* * **Blocking**
* * **Non- thread safe**

### Keep the code DRY

**Avoid duplication of code between different Sources, Sinks and Flows. Extract the common logic to a common abstract base `GraphStageLogic` that is inherited by all the `GraphStage`.**

**Another good approach, in some cases, is to implement the Source or the Sink using a flow:**
* **Source --> Source.maybe.viaMat(MyFlow)(Keep.right)**
* **Sink --> MyFlow.toMat(Sink.ignore)(Keep.right)**

### Flow considerations

When designing Flows, consider adding an extra field to the in- and out-messages which is passed through. A common
use case we see, is committing a Kafka offset after passing data to another system.

## Test

**Write tests for all public methods and all possible settings.**

**Use docker containers for any testing needed by your application. The container's configuration can be added to the `docker-compose.yml` file.
Please ensure that you limit the amount of resources used by the containers if necessary.**

## Documentation

Using Paradox syntax, create or complement the documentation in the docs module **so it include all public methods and settings**.
Prepare code snippets to be integrated by Paradox in the tests.
**Such example should be part of real tests and no in unused methods.**

Use ScalaDoc if you see the need to describe the API usage better than the naming does.

**Comment by juanjoDiaz** [comment]
@ennru Are you creating a PR?
Would you like me to create a PR with my extended proposal?

Wdyt?

**Comment by ennru** [comment]
I might get to it tomorrow.
