### ISSUE TITLE
JmsConsumer.ackSource fails to shutdown (or abort) when messages are not acknowledged

### ISSUE THREAD

**Issue by matthedude** [akka/alpakka#820]
To be more specific it appears that if the number of messages consumed by the `JmsConsumer.ackSource` and not acknowledged is greater than the `bufferSize` the stream never completes when the `KillSwitch` is used to `shutdown` or `abort`.
An easy way to see this is to go to the `JmsConnectorsSpec` and comment out `env.acknowledge()` in the `lose some elements when aborting a stream` test. The `streamDone` `Future` never completes.

I can provide a condensed example if this is not clear, I have observed streams completing where the number of messages not acknowledged is less than or slightly over the `bufferSize`, I guess the problem occurs when backpressure kicks in but I don't have any greater insights yet.

**Comment by johanandren** [comment]
Would you be up for PR:ing a fix perhaps, given that you have already spent time figuring it out?

**Comment by matthedude** [comment]
@johanandren definitely if I figure it out the fix, I created the issue in case someone with more experience with the lib had more information. I'll let you know if I have any luck with it 👍

**Comment by johanandren** [comment]
Great, thanks for both reporting and giving it a shot!

**Comment by akara** [comment]
Unacknowledged messages at closing connection should cause these messages to be re-delivered. That's the theoretical part.

However, the ActiveMQ client can take a very long time to close a connection, or even won't close the connections in such cases. If you trace down the issue and it is due to ActiveMQ client closing connection hanging forever, I'd argue this is an ActiveMQ issue. However, if we see our code somehow else does not complete the Future, then it is definitely our issue to fix.

**Comment by matthedude** [comment]
Hi @akara - I think I've traced it down to the ActiveMQ client closing connection hanging forever but because the `take` operation on the `ackQueue` is blocking forever (as no messages are in it in this scenario). I've made a PR [here](https://github.com/akka/alpakka/pull/822/files) it would be great if you could look at it as you're more of an expert than me (thanks for doing all the acknowledgement and transaction work by the way!)

**Comment by ennru** [comment]
Solved with #822
