### ISSUE TITLE
AWS DynamoDB Connector not working

### ISSUE THREAD

**Issue by psriramula** [akka/alpakka#855]
Hi,

I am facing compilation issues while creating a table by following the quick start guide.

`Source
  .single(new CreateTableRequest().withTableName("testTable").toOp)
  .via(client.flow)
  .map(_.getTableDescription.getTableArn)`

From the above code, I faced compilation with 

`.single(new CreateTableRequest().withTableName("testTable").toOp)`

and tweaked it to 
`client.source(new CreateTableRequest().withTableName("testTable").toOp)`

and yet facing issues with **.toOp**

**Comment by raboof** [comment]
This might be a good question to ask at https://discuss.lightbend.com/c/akka/streams-and-alpakka ?

More example code and the exact compiler error message would help.

**Comment by psriramula** [comment]
@raboof: thanks for your message in simple words, I don't see any full-fledged  CRUD example for AWS Dynamo DB Connector, hence I am working with https://github.com/panosGel/fuzzy-bassoon/blob/develop/src/main/scala/com/fuzzy/akka/dbreader/DynamoDBReaderWriter.scala#L60-L66 and adding a create Table feature by following  steps in 
https://developer.lightbend.com/docs/alpakka/current/dynamodb.html

**Comment by psriramula** [comment]
@raboof  Any fully working sample with AWS Dynamo DB Connector with full CRUD will be greatly appreciated.

**Comment by raboof** [comment]
@psriramula our issue tracker is meant to track bugs and feature requests, not for general questions. For those, please use the forums mentioned above. When you ask the question there, your chances of a useful answer are much bigger if you share the exact code you wrote and the exact compiler error that you got for that code.

I agree an AWS Dynamo DB connector example project would be great, would you be interested in contributing one once you have solved your problems?

Closing this issue for now, please ask the question at the forums, and feel free to re-open this issue when it turns out this is a problem with alpakka after all.

**Comment by psriramula** [comment]
@raboof : thanks for update closing.
